In [162]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
df=pd.read_csv('economic_index.csv')

In [163]:
df

Unnamed: 0  year  month  interest_rate  unemployment_rate  index_price
0            0  2017     12           2.75                5.3         1464
1            1  2017     11           2.50                5.3         1394
2            2  2017     10           2.50                5.3         1357
3            3  2017      9           2.50                5.3         1293
4            4  2017      8           2.50                5.4         1256
5            5  2017      7           2.50                5.6         1254
6            6  2017      6           2.50                5.5         1234
7            7  2017      5           2.25                5.5         1195
8            8  2017      4           2.25                5.5         1159
9            9  2017      3           2.25                5.6         1167
10          10  2017      2           2.00                5.7         1130
11          11  2017      1           2.00                5.9         1075
12          12  2016     12           2.00                6.0         1047
13          13  2016     11           1.75                5.9          965
14          14  2016     10           1.75                5.8          943
15          15  2016      9           1.75                6.1          958
16          16  2016      8           1.75                6.2          971
17          17  2016      7           1.75                6.1          949
18          18  2016      6           1.75                6.1          884
19          19  2016      5           1.75                6.1          866
20          20  2016      4           1.75                5.9          876
21          21  2016      3           1.75                6.2          822
22          22  2016      2           1.75                6.2          704
23          23  2016      1           1.75                6.1          719

In [164]:
df.drop(columns=['Unnamed: 0','year','month'],inplace=True)

In [165]:
#Here the interest_rate and unemployment_rate are the independent features and iondex_price is the dependent feature
df.head()


interest_rate  unemployment_rate  index_price
0           2.75                5.3         1464
1           2.50                5.3         1394
2           2.50                5.3         1357
3           2.50                5.3         1293
4           2.50                5.4         1256

In [166]:
df.isnull().sum()

interest_rate        0
unemployment_rate    0
index_price          0
dtype: int64

In [167]:
# visualization
sns.pairplot(df)

In [168]:
df.corr()

interest_rate  unemployment_rate  index_price
interest_rate           1.000000          -0.925814     0.935793
unemployment_rate      -0.925814           1.000000    -0.922338
index_price             0.935793          -0.922338     1.000000

In [169]:
plt.scatter(df['interest_rate'],df['unemployment_rate'])
plt.xlabel('Index_rate')
plt.ylabel('Unemployment_rate')

Text(0, 0.5, 'Unemployment_rate')

In [170]:
# independent and dependent features
x=df[['interest_rate','unemployment_rate']]
y=df[['index_price']]

In [171]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [172]:
sns.regplot(x=df['interest_rate'],y=df['index_price'])

<Axes: xlabel='interest_rate', ylabel='index_price'>

In [173]:
from sklearn.preprocessing import StandardScaler

In [174]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [175]:
x_test

array([[ 0.36115756, -0.82078268],
       [-1.08347268,  1.33377186],
       [ 1.8057878 , -1.43636969],
       [-1.08347268,  1.02597835],
       [-0.36115756,  0.41039134],
       [ 0.36115756, -0.51298918]])

In [176]:
x_train.shape

(18, 2)

In [177]:
from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(x_train,y_train)

LinearRegression()

In [178]:
# cross validation
from sklearn.model_selection import cross_val_score
val_score=cross_val_score(regression,x_train,y_train,cv=3)

In [179]:
np.mean(val_score)

0.8541426890278223

In [180]:
# prediction
y_pred=regression.predict(x_test)
y_pred

array([[1180.7466813 ],
       [ 802.74279699],
       [1379.83457045],
       [ 838.52599602],
       [ 973.85313963],
       [1144.96348227]])

In [181]:
# performance metrics
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [182]:
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mse)
print(mse)
print(mae)
print(rmse)

8108.567426306611
73.80444932337099
90.04758423359624


In [183]:
plt.scatter(y_test,y_pred)

In [184]:
# residuals
residuals=y_test-y_pred
residuals

index_price
8    -21.746681
16   168.257203
0     84.165430
18    45.474004
11   101.146860
9     22.036518

In [185]:
# plotting residuals
sns.displot(residuals,kind='kde')

#  if this graph is a normal distribution graph , that means ur model is doing great 

In [186]:
#  plotting predicted values and residuals
plt.scatter(y_pred,residuals)
plt.xlabel('Y_pred')
plt.ylabel('Residuals')

Text(29.0, 0.5, 'Residuals')

In [189]:
## OLS Linear Regression
import statsmodels.api as sm
model=sm.OLS(y_train,x_train).fit()

In [191]:
model.summary()

c:\Users\Nitin\anaconda3\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=18
  res = hypotest_fun_out(*samples, **kwds)


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:            index_price   R-squared (uncentered):                   0.035
Model:                            OLS   Adj. R-squared (uncentered):             -0.086
Method:                 Least Squares   F-statistic:                             0.2880
Date:                Mon, 14 Jul 2025   Prob (F-statistic):                       0.754
Time:                        13:06:36   Log-Likelihood:                         -150.85
No. Observations:                  18   AIC:                                      305.7
Df Residuals:                      16   BIC:                                      307.5
Df Model:                           2                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            88.2728    658.295      0.134      0.895   -1307.250    1483.796
x2          -116.2572    658.295     -0.177      0.862   -1511.780    1279.266
==============================================================================
Omnibus:                        0.598   Durbin-Watson:                   0.007
Prob(Omnibus):                  0.741   Jarque-Bera (JB):                0.567
Skew:                          -0.361   Prob(JB):                        0.753
Kurtosis:                       2.517   Cond. No.                         4.78
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [192]:
regression.coef_

array([[  88.27275507, -116.25716066]])

In [193]:
regression.intercept_

array([1053.44444444])